from setuptools import setup, find_packages

setup(
    name="cernoid-backend",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "fastapi",
        "sqlalchemy",
        "aiosqlite",
        "pydantic",
        "python-jose",
        "passlib",
        "python-multipart",
        "uvicorn",
        "redis",
        "numpy",
        "opencv-python",
        "dlib",
        "face-recognition",
        "tensorflow",
        "torch",
        "scikit-learn",
        "psutil",
        "plotly",
        "pandas",
        "scipy",
    ],
    python_requires=">=3.10",
) 