extends: default.yaml

database:
  host: localhost
  debug: true

logging:
  level: DEBUG
  handlers:
    file:
      enabled: false

security:
  cors:
    allowed_origins: ["http://localhost:3000", "http://localhost:8080"]

api:
  debug: true 