extends: default.yaml

database:
  name: cernoid_test
  pool_size: 5

recognition:
  confidence_threshold: 0.75
  cache:
    enabled: false

camera:
  streams:
    - name: test_camera
      url: mock://camera
      enabled: true

logging:
  level: DEBUG
  handlers:
    file:
      enabled: false
    console:
      enabled: true

security:
  jwt:
    secret_key: test_secret

api:
  port: 8001 