# CernoID Configuration File

# Base Directory Configuration
BASE_DIR: "C:/Users/maces/CernoID-Complete-1"

# Image Processing Configuration
IMAGE_FOLDER: "C:/Users/maces/CernoID-Complete-1/data/images"
SHAPE_PREDICTOR_PATH: "models/shape_predictor_68_face_landmarks.dat"
FACE_RECOGNIZER_PATH: "models/dlib_face_recognition_resnet_model_v1.dat"

# Logging Configuration
LOGS_PATH: "logs/app.log"

# Database Configuration
DATABASE_CONFIG:
  host: "localhost"
  port: 5432
  database: "cernoid"
  user: "postgres"
  password: "default_password"  # Change this in production

# Security Settings
SECURITY:
  JWT_SECRET: "your-secret-key-here"  # Change this in production
  TOKEN_EXPIRE_MINUTES: 60
  CORS:
    ALLOWED_ORIGINS: ["*"]
    ALLOWED_METHODS: ["*"]

# Notification Settings
NOTIFICATIONS:
  SMS_ENABLED: true
  EMAIL_ENABLED: true
  TWILIO:
    ACCOUNT_SID: "your-account-sid"  # Change this in production
    AUTH_TOKEN: "your-auth-token"    # Change this in production
  SENDGRID:
    API_KEY: "your-api-key"         # Change this in production 