name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run backend tests with coverage
        run: |
          pytest backend/tests/ --cov=backend/src --cov-report=xml --cov-report=term-missing

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests with coverage
        working-directory: frontend
        run: npm test -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            coverage.xml
            frontend/coverage/

      - name: Check coverage thresholds
        run: |
          python -c "
          import xml.etree.ElementTree as ET
          import sys
          
          # Parse coverage XML
          tree = ET.parse('coverage.xml')
          root = tree.getroot()
          
          # Get overall coverage
          coverage = float(root.attrib['line-rate']) * 100
          
          # Check if coverage meets threshold
          if coverage < 80:
              print(f'Backend coverage ({coverage:.2f}%) is below threshold (80%)')
              sys.exit(1)
          "
        shell: python

      - name: Check frontend coverage
        working-directory: frontend
        run: |
          COVERAGE=$(node -e "const coverage = require('./coverage/coverage-summary.json'); console.log(coverage.total.lines.pct);")
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Frontend coverage ($COVERAGE%) is below threshold (80%)"
            exit 1
          fi 